In [2]:
import pandas as pd

In [5]:
df=pd.read_csv("Spotify Most Streamed Songs.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
 24  cover_url             953 non-null    object
dtypes: int64(17), object(8)
memory usage: 186.3+ KB

In [7]:
df[df["released_year"]>2020]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,B,Major,80,89,83,31,0,8,4,Not Found
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,C#,Major,71,61,74,7,0,10,4,https://i.scdn.co/image/ab67616d0000b2730656d5...
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,F,Major,51,32,53,17,0,31,6,https://i.scdn.co/image/ab67616d0000b273e85259...
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,A,Minor,65,23,80,14,63,11,6,https://i.scdn.co/image/ab67616d0000b273ab5c9c...
5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,67,...,C#,Major,92,66,58,19,0,8,24,https://i.scdn.co/image/ab67616d0000b273e3a09a...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,A,Major,60,24,39,57,0,8,3,https://i.scdn.co/image/ab67616d0000b2730f5397...
949,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,F#,Major,42,7,24,83,1,12,6,https://i.scdn.co/image/ab67616d0000b273e0b60c...
950,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,C#,Major,80,81,67,4,0,8,6,Not Found
951,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,C#,Major,82,67,77,8,0,12,5,Not Found
952,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,E,Minor,61,32,67,15,0,11,5,https://i.scdn.co/image/ab67616d0000b273992a1f...

In [8]:
df.sort_values("streams",ascending=False)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,cover_url
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,1,1970,1,1,2877,0,BPM110KeyAModeMajorDanceability53Valence75Ener...,16,...,A,Major,53,75,69,7,0,17,3,https://i.scdn.co/image/ab67616d0000b2739a0011...
33,Anti-Hero,Taylor Swift,1,2022,10,21,9082,56,999748277,242,...,E,Major,64,51,63,12,0,19,5,https://i.scdn.co/image/ab67616d0000b273bb54dd...
625,Arcade,Duncan Laurence,1,2019,3,7,6646,0,991336132,107,...,A,Minor,45,27,33,82,0,14,4,https://i.scdn.co/image/ab67616d0000b273a95440...
253,Glimpse of Us,Joji,1,2022,6,10,6330,6,988515741,109,...,G#,Major,44,27,32,89,0,14,5,https://i.scdn.co/image/ab67616d0000b27308596c...
455,Seek & Destroy,SZA,1,2022,12,9,1007,0,98709329,5,...,C#,Major,65,35,65,44,18,21,7,https://i.scdn.co/image/ab67616d0000b27370dbc9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,Revenge,XXXTENTACION,1,2017,8,25,3600,11,1022258230,7,...,B,Minor,75,18,25,78,0,11,26,https://i.scdn.co/image/ab67616d0000b273203c89...
744,Right On,Lil Baby,1,2022,4,8,1116,0,101780047,31,...,D,Major,70,22,61,2,0,10,34,https://i.scdn.co/image/ab67616d0000b2736c6827...
515,Best Friends,The Weeknd,1,2022,1,7,1292,0,101114984,3,...,E,Minor,49,49,59,44,0,35,21,https://i.scdn.co/image/ab67616d0000b2734ab252...
500,ýýýabcdefu,Gayle,1,2021,8,13,7215,0,1007612429,170,...,E,Major,70,42,54,30,0,37,5,Not Found
301,"Arcï¿½ï¿½ngel: Bzrp Music Sessions, Vol","Arcangel, Bizarrap",2,2023,3,22,654,3,100409613,11,...,B,Minor,72,79,78,55,0,15,30,Not Found

In [14]:

df.groupby("artist(s)_name")["streams"].sum().sort_values(ascending=False).head(1)

artist(s)_name
Edison Lighthouse    BPM110KeyAModeMajorDanceability53Valence75Ener...
Name: streams, dtype: object

In [18]:
df.groupby("artist(s)_name")["streams"].sum().sort_values(ascending=False).head(5)

artist(s)_name
Edison Lighthouse                BPM110KeyAModeMajorDanceability53Valence75Ener...
Duncan Laurence                                                          991336132
Joji                                                  9885157412463900681122364376
Sofia Carson                                                              97610446
Lost Frequencies, Calum Scott                                            972509632
Name: streams, dtype: object